#!/bin/bash

function display_error () {
	ssft_display_error ERROR "$@"
	exit 1
}

function display_wired_or_wireless () {
	local tit msg
	tit="Network Type"
	msg="What type of network would you like to setup?"
	ssft_select_single "$tit" "$msg" "$@"
}

function display_iface_list () {
	local tit msg type
	type=$1
	shift
	tit="Choose Network Device"
	msg="What $type device is to be configured?"
	ssft_select_single "$tit" "$msg" "$@"
}
