#!/bin/bash

#LIBPATH=/usr/lib/netcardconfig-kanotix
LIBPATH=$PWD

NICINFO=$LIBPATH/nicinfo.awk

function get_netdev_valid_ifaces () {
	if [[ ! -d /sys/class/net ]]
	then
		return
	fi
	local count netdev_type
	pushd /sys/class/net >/dev/null
		for i in *
		do
			((count++))
			netdev_type=$(awk -f $NICINFO $i type)
			case $netdev_type in
				wired)
					WIRED_IFACES[$count]=$i
					;;
				wireless)
					WIRELESS_IFACES[$count]=$i
					;;
			esac
		done
	popd >/dev/null
}

function get_netdev_description () {
	local count desc
	for i in "$@"
	do
		((count++))
		desc=$(awk -f $NICINFO $i desc)
		IFACE[$count]="$i    [$desc]"
	done
}
